name: Enviar correo al subir cambios
on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Configuración de correos
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: bernax123321@gmail.com
          password: lhoayihxsnnopxeu
          from: bernax123321@gmail.com
          subject: "Cambios subidos a rama ${{ github.ref_name }}"
          to: bernardoorozcoquirarte@gmail.com, aurag0480@gmail.com
          body: |
            Hola,

            Se han realizado cambios en la rama ${{ github.ref_name }} del repositorio.

            Saludos,
            Tu repositorio automatizado.
