name: Enviar correo al subir cambios
on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Configuración de correos
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: bernie
          password: lhoayihxsnnopxeu
          from: bernax123321@gmail.com
          subject: "Cambios subidos a rama main"
          to: bernardoorozcoquirarte@gmail.com
          body: "Se han realizado cambios en la rama main del repositorio."
